### ISSUE TITLE
Installation instruction for pip are missing

### ISSUE THREAD

**Issue by milosevic** [informalsystems/atomkraft#177]
To make installation process as simple as possible we should add also instructions for the pip.

**Comment by rnbguy** [comment]
`pip` is pretty standard package in any popular Os. Any default package manager, came with user's machine, should support it.

Otherwise, we can add links to
- Official python docs https://packaging.python.org/en/latest/tutorials/installing-packages/#ensure-you-can-run-pip-from-the-command-line
- Office pip docs - https://pip.pypa.io/en/stable/installation

Do these help?

But, in the worst case, we should assume any kind of breakage. If you faced any issues while installing `pip` or running `pip install atomkraft`, please report so that we can update docs accordingly.
