### ISSUE TITLE
CLI: `trace` command

### ISSUE THREAD

**Issue by hvanz** [informalsystems/atomkraft#8]
## Background/Motivation

A user has written a TLA+ model and wants to generate some traces from test assertions from the model, so that they can use some of the generated test traces later for executing on a testnet.

**Linked documents:** 
- [CLI ADR](https://github.com/informalsystems/atomkraft/blob/andrey/adr-cli/docs/src/01adr-cli.md)

## Description

The `atomkraft trace` command generates ITF traces. If no model is given as parameter, it will use a model already loaded in memory with the `atomkraft model` command.
Its format is:
```
atomkraft trace [--model=<model>] <config-path> <test-assertion> [<traces-path>]
```
where:
- `<config-path>` is the (path to) TOML file with the model and model checker configuration;
- `<test-assertion>` is the name of the model operator describing the desired test trace.
- `<traces-path>` is the location for the trace files

Upon successful command execution, the generated test trace in the ITF format should be persisted to disk.

A model config is a TOML file with the following format, and located in the same directory as the model:
```
[Model]
name = "ModuleName"
init = "Init"
next = "Next"
spec = "Spec"
invariants = ["Inv1", "Inv2", ...]
tlc_config_file = "path/to/ModuleName.cfg"

[Constants]
constant_name_1 = "tla_constant_value_1"
...
constant_name_n = "tla_constant_value_n"

[Config]
check_deadlock = FALSE
length=10 # called depth in TLC
```

### Related commands:
```
atomkraft config traces-dir <traces-path> # sets the location for the generated trace files
atomkraft config traces-dir # displays the current directory for the trace files
```

## Technical details

Under the hood, the `atomkraft trace` command will call the following Modelator Shell commands:
```
model = ModelShell.parse_file(<model-path>)
model.typecheck()
config = ModelConfig.parse_file(<config-path>)
model.check(config, <test-assertion>, <traces-path>)
```
where `ModelConfig` would be a new class in Modelator, used as a common data structure for Apalache and TLC configurations.

## Artifacts

This command generates ITF traces in the directory `default_traces_dir` provided by the Setup module.

## Interface to other modules

- Read the value of `default_traces_dir` provided by the Setup module.

## Dependencies

- `model` command https://github.com/informalsystems/atomkraft/issues/17

## Tasks

- [ ] Implement the `trace` command (making use of Modelator, as described above).
- [ ] Add unit tests for `trace`.

**Comment by ivan-gavran** [comment]
I like that you are explicit about adding tests :DDD

The overall description looks good, but I have one major comment: you are probably going too broadly with thinking about a general `ModelConfig` structure already in the scope of this issue. 
Exactly because this is an important topic, we should leave it out of this first, early prototype. (Given that we also decided to [support only Apalache short term](https://github.com/informalsystems/modelator/issues/214).) 

Perhaps it still makes sense to write a `ModelConfig` structure as a placeholder, but I would advise not to try to push TLC-specific values there yet.
The early ADR draft on the preprocessor component ([here](https://github.com/informalsystems/modelator/pull/221/files)) that I am working on was trying to identify what are those basic values, so maybe this can be an inspiration.

**Comment by hvanz** [comment]
I agree. We can just require the minimum to make `ModelConfig` just a small layer on top of Apalache, but that we can also expand later to TLC. I updated the issue on `ModelConfig` https://github.com/informalsystems/modelator/issues/218
